improve Readme
delta-leonis/frosty pull request #16
Opened 2017-11-02 20:42 UTC by Vnkn0wn

2017-11-06 09:47 UTC, romni submitted a review, later dismissed

2017-11-06 14:33 UTC, thumbnail requested changes
Please fully address #12 and add the `LICENSE` file as well.

2017-11-09 19:26 UTC, RyanMeulenkamp requested changes

2017-11-09 19:26 UTC, RyanMeulenkamp commented on readme.md
> +# `frosty`
Do away with the `.
Also, there's no newline here, but there is one after other headers.

2017-11-09 19:26 UTC, RyanMeulenkamp commented on readme.md
> +The javadoc for the current code on `master` can be found on https://delta-leonis.github.io/frosty/
```Markdown
The javadoc for the current code on `master` can be found [here](https://delta-leonis.github.io/frosty/).
```

2017-11-09 19:52 UTC, thumbnail approved these changes

2017-11-09 19:53 UTC, RyanMeulenkamp approved these changes

2017-11-09 19:53 UTC, merged