Fix naming and directory structure
delta-leonis/frosty pull request #9
Opened 2017-10-24 07:10 UTC by RyanMeulenkamp

2017-10-24 07:14 UTC, thumbnail commented on readme.md
> +# frosty
I just gave you (temporary) admin rights for this repo. Can you make sure the repo description and change the name.

2017-10-24 07:15 UTC, thumbnail commented on src/native/cpp/library.h
> + *       com.copilot.frosty.GamePadManager.hookGamePadListener method.
wrong name

2017-10-24 07:15 UTC, thumbnail commented on src/native/cpp/library.h
> +JNICALL Java_com_copilot_frosty_GamePadManager_hookGamePadListener(
wrong name

2017-10-24 07:17 UTC, thumbnail requested changes
Please update the c-code accordingly. Also i can't see how this compiled on your machine since the naming isn't synchronized between the c- and java-project. 

Also this PR contained alot of added `final` statements. which should've been in #2

2017-10-25 11:40 UTC, thumbnail submitted a review, later dismissed

2017-10-25 11:41 UTC, thumbnail commented
Since #10 hasn't been fixed yet I can't verify whether this PR is safe to merge; because `make` doesn't work locally. Could you describe the build steps?

2017-10-25 11:47 UTC, thumbnail commented
I also noticed you use your company email for this repository; you can change that setting on a repository base using `git config user.email "ryan.meulenkamp@gmail.com"`.

2017-10-25 13:26 UTC, RyanMeulenkamp commented
Steps to build:
```Shell 
cd ${PROJECT_DIR}/src/native/cpp
cmake . 
make
```

In Intellij, create a build configuration. Add the following vm parameter: `-Djava.library.path=/build`

2017-10-26 06:48 UTC, thumbnail commented
Could you move 47643b3 to another PR so we can merge the rename PR separately?

2017-10-26 06:52 UTC, RyanMeulenkamp commented
Done

2017-10-26 07:00 UTC, thumbnail approved these changes
Catchy name. we might need a logo in the near future :)

2017-10-26 07:00 UTC, merged

2017-10-26 07:01 UTC, romnous commented on readme.md
> -## License
no license for this project?

2017-10-26 07:01 UTC, romnous commented on src/main/java/io/leonis/frosty/GamePadAxis.java
> +  GamePadAxis(final int value) {
no explicit access modifier?

2017-10-26 07:01 UTC, romnous commented on src/main/java/io/leonis/frosty/GamePadAxis.java
> +  public static GamePadAxis fromValue(final int value) {
is this secretly a constructor?

2017-10-26 07:02 UTC, thumbnail commented on src/main/java/io/leonis/frosty/GamePadAxis.java
> +  GamePadAxis(final int value) {
for an enum?